### ISSUE TITLE
Failed to get module addresses  exiting..

### ISSUE THREAD

**Issue by Mikilis** [crisptothemax/csgo-external-base#1]
Failed to get module addresses  exiting..

**Comment by TsuNamiPlayZ** [comment]
same

**Comment by crisptothemax** [comment]
Its because the game changed it from panorama to normal again

**Comment by lukeacat** [comment]
@crisptothemax Could this be reopened?
Same thing happening
I updated hazedumper

**Comment by lukeacat** [comment]
Make sure to build in x86 + Release and it works perfectly!!
